/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://vwhwe5ub5fgs5laqmhx5kplgby.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fxhskfjwanakldyq75rdfyl7ra",
    "aws_cognito_identity_pool_id": "us-east-1:f95d08c5-4fea-4e51-b546-edcdbb6a27d8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8kricD2Nr",
    "aws_user_pools_web_client_id": "25o4sf6ahlhj4mv9l2pv9rgaks",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
